# Generated by Django 3.2.9 on 2021-11-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211118_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='inflamation',
            field=models.FloatField(verbose_name='Inflamacion'),
        ),
    ]
